# Generated by Django 3.0.8 on 2020-07-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='hits',
        ),
        migrations.AlterField(
            model_name='board',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='language',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='board',
            name='memo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='board',
            name='subject',
            field=models.CharField(max_length=10),
        ),
    ]
